apiVersion: apps/v1
kind: Deployment
metadata:
  name: redirect-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redirect-service
  template:
    metadata:
      labels:
        app: redirect-service
    spec:
      containers:
      - name: redirect-service
        image: redirect-service:latest
        ports:
        - containerPort: 8080
