apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortener-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shortener-service
  template:
    metadata:
      labels:
        app: shortener-service
    spec:
      containers:
      - name: shortener-service
        image: shortener-service:latest
        ports:
        - containerPort: 8080
