# Default values for shortener-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: shortener-service
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
