# Default values for api-gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: api-gateway
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
